version: "3.5"
services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./prom-data:/prometheus
    container_name: prometheus
    hostname: prometheus
    command:
      - --storage.tsdb.path=/prometheus
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    ports:
      - 127.0.0.1:9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - vm_net

  grafana:
    container_name: grafana
    image: grafana/grafana:9.3.6
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./var/lib/grafana:/var/lib/grafana
    networks:
      - vm_net
    restart: always
    user: "0:0"

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 127.0.0.1:9100:9100
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - vm_net

  alertmanager:
    image: prom/alertmanager
    ports:
      - 127.0.0.1:9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      - vm_net

networks:
  vm_net: